---
abstract: 'perform jQuery-like queries on HTML::Element trees'
author:
  - 'Kevin Kamel <kamelkev@mailermailer.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Query
no_index:
  directory:
    - t
    - inc
requires:
  Badger: 0.03
  HTML::Tree: 3.23
version: 0.09
